### ISSUE TITLE
API not accessible due Cloudflare anti-bot protection

### ISSUE THREAD

**Issue by Stormheg** [djangopackages/djangopackages#1352]
**Describe the bug**
Wagtail.org uses the djangopackages.org API to retrieve packages related to Wagtail and [show them on wagtail.org.](https://wagtail.org/packages/) We use this endpoint for that: `https://djangopackages.org/api/v4/grids/?q=wagtail`

Since recently (a couple weeks? unsure when it last worked) our import script can no longer access this url due to Cloudflare 'just a moment' page anti-bot protection mechanism kicking in. This only happens from our Heroku hosting provider, not from other IP addresses that I have tested.

**To Reproduce**

Run this curl command from a 'suspect' IP address

```
curl -I https://djangopackages.org/api/v4/grids/?q=wagtail
```

<details>

```
HTTP/2 403 
date: Wed, 19 Feb 2025 22:02:01 GMT
content-type: text/html; charset=UTF-8
accept-ch: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA
cf-mitigated: challenge
critical-ch: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
permissions-policy: accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
server-timing: chlray;desc="914989f0aaf9bdb1"
x-content-options: nosniff
x-frame-options: SAMEORIGIN
cf-chl-out: spds7cKK1+zFTNBLCowE4hD3TSnHtXlI4SXNuNSdEb6NBRuii3JFc1/G9L6pMGou9w8xcn8hcHTH18K3KkjQQSwwz68CTcZloq/RYfDicwK93a2bIGAJkIynl6sjnVLY$vsg8e2bZZamtwGap0t37wg==
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=5rGDyoyzz3pDoY09oX0ijUcGRrZgiw2Y3M9kvwHvHuKZ6k5GoR%2FSjpeZ0cNPbr%2FxPa1N9BHIUkMq1BIBjZZaF6PoXOrNwaw%2FdDIz9wUwQgHt9RKZpC27ZRCsFnqq9BDSKrO03Bk%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 914989f0aaf9bdb1-DUB
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=1537&min_rtt=1509&rtt_var=453&sent=5&recv=8&lost=0&retrans=0&sent_bytes=3428&recv_bytes=802&delivery_rate=1919151&cwnd=235&unsent_bytes=0&cid=9d0caf05a746ab20&ts=31&x=0"
```

</details>

**Expected behavior**

The request to not be blocked. Can API endpoints be excluded from anti-bot protection?

**Comment by jefftriplett** [comment]
@Stormheg hey Storm, sorry it took me a bit to see this. Do you have an IP or something we can allow list? Happy to look, but I don't foresee rolling back any bot protection for the overall quality of the website.

**Comment by Stormheg** [comment]
@jefftriplett according to Heroku support, the [IP addresses used are highly dynamic and the IP ranges cover whole AWS regions](https://help.heroku.com/JS13Y78I/i-need-to-add-heroku-dynos-to-our-allowlist-what-are-ip-address-ranges-in-use-at-heroku) - whitelisting doesn't sound like it would help both of us much.

As another alternative, perhaps an authenticated API endpoint can be created that is excluded from anti-bot protections?

**Comment by jefftriplett** [comment]
@Stormheg I made a few rules changes to try to open up the v4. Would you mind trying to curl it again? 

Curl worked for me both before and after these changes so I'm not sure.

**Comment by Stormheg** [comment]
@jefftriplett no dice, still 403'ng

curl -I https://djangopackages.org/api/v4/grids/?q=wagtail

<details>
HTTP/2 403 
date: Fri, 14 Mar 2025 13:34:50 GMT
content-type: text/html; charset=UTF-8
accept-ch: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA
cf-mitigated: challenge
critical-ch: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
permissions-policy: accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
server-timing: chlray;desc="9204269f6b6b34c6"
x-content-options: nosniff
x-frame-options: SAMEORIGIN
cf-chl-out: abfo1MRJKeZiEWQPSefI1aAZcO6zYLgkeKdQsEUQFIzUfulATBdcj7x/B3OhtBKVGelL+gG6swHg56BerdFZBkxxhaLYJJ6/B8YewcIj5Vkcm2r12VRgFcSoOn6Ulru/$0SMxSqNBAyPCf/k6DkI+dw==
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=eLH5sTNDRp6lEQl49%2F0dXaFy3bJM6knuyeocvPkLN66EuVBnmXRKSB2ZrCh3SVhfYowFqdWBa7fwxa0B45M4k%2F2Qdljewz1%2BnNg0cgQzxO43rMggE66GZoO95UOfzVeQAsTChxg%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 9204269f6b6b34c6-DUB
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=1727&min_rtt=1718&rtt_var=498&sent=5&recv=8&lost=0&retrans=0&sent_bytes=3408&recv_bytes=802&delivery_rate=1685681&cwnd=248&unsent_bytes=0&cid=bb62d827d88b87a1&ts=52&x=0"
</details>

Today the Dyno's ip address appears to be `34.255.199.23`

**Comment by jefftriplett** [comment]
@Stormheg lets try one more time. Some checkboxes were unchecked and I added the IP range. Maybe between the two we are good. 🤞 

If that doesn't work, we'll try an auth endpoint and clean it up while we are in there.

**Comment by Stormheg** [comment]
No dice

**Comment by jefftriplett** [comment]
Is the code that fetches it public? 

I might have some better luck testing it from a remote server than asking you to curl every 5 minutes 😬

**Comment by jefftriplett** [comment]
To make matters weirder, I just tested on six remote servers for about 10 to 20 curl-calls each and I get 200s.

**Comment by Stormheg** [comment]
@jefftriplett from this line onwards https://github.com/wagtail/wagtail.org/blob/a5e5aac8a5e46ba1a2d69af9d54f364518197ec9/wagtailio/packages/views.py#L12

**Comment by Stormheg** [comment]
@jefftriplett have you tried making the request from an AWS ip range?

**Comment by jefftriplett** [comment]
> [@jefftriplett](https://github.com/jefftriplett) have you tried making the request from an AWS ip range?

I don't have an AWS account to work from. 

I tried from DO, Hetzner, and my small fleet of Macs + RPi + Nuc I have deployed across a few physical locations.

**Comment by Stormheg** [comment]
@jefftriplett still not - please lets go with an alternative

**Comment by jefftriplett** [comment]
I finally found something in the logs: 

```
  {
    "action": "managed_challenge",
    "clientASNDescription": "AMAZON-02",
    "clientAsn": "16509",
    "clientCountryName": "IE",
    "clientIP": "63.32.91.194",
    "clientRefererHost": "",
    "clientRequestHTTPHost": "djangopackages.org",
    "clientRequestHTTPMethodName": "GET",
    "clientRequestHTTPProtocol": "HTTP/1.1",
    "clientRequestPath": "/api/v4/grids/",
    "clientRequestQuery": "?q=wagtail",
    "datetime": "2025-03-20T03:00:33Z",
    "ref": "",
    "rayName": "9231f5bdbfa0be43",
    "ruleId": "bot_fight_mode",
    "description": "",
    "rulesetId": "",
    "source": "botFight",
    "userAgent": "python-requests/2.32.3",
    "matchIndex": 0,
    "metadata": [],
    "sampleInterval": 1
  },
```

I updated with the IP to see if that will short-term work. 

I'm on vacation for the rest of the week, so I won't make any progress toward adding auth until next week.

**Comment by ryancheley** [comment]
This is also related to a [discussion](https://github.com/djangopackages/djangopackages/discussions/1355) and would appear to help a couple of use cases

**Comment by ryancheley** [comment]
@jefftriplett I was looking at the docs for CloudFlare and found [this](https://developers.cloudflare.com/bots/get-started/free/#limitations)

> You cannot bypass or skip Bot Fight Mode using the Skip action in WAF custom rules or using Page Rules. Skip, Bypass, and Allow actions apply to rules or rulesets running on the [Ruleset Engine](https://developers.cloudflare.com/ruleset-engine/). While Super Bot Fight Mode rules are implemented in the Ruleset Engine, Bot Fight Mode checks are not. This is why you can skip Super Bot Fight Mode, but not Bot Fight Mode. If you need to skip Bot Fight Mode, consider using [Super Bot Fight Mode](https://developers.cloudflare.com/bots/get-started/pro/).

Based on the log message [posted previously](https://github.com/djangopackages/djangopackages/issues/1352#issuecomment-2740455164) it looks like Bot Fight Mode is on. Not sure if we can migrate to Super Bot Fight Mode and see if that resolves the issue 🤷

**Comment by jefftriplett** [comment]
Here is what is set: 

<img width="950" alt="Image" src="https://github.com/user-attachments/assets/28f4053e-fc19-4f9b-9db6-7b379ab2fc74" />

**Comment by jefftriplett** [comment]
I re-toggled the state on this while Ryan is looking.

I think our next steps might be pulling the Wagtail update script and running it vs. curl. There has to be something non-obvious going on. I could see Cloudflare blocking Request's default user agent, which appears to be disabled.

**Comment by ryancheley** [comment]
I did some testing by creating EC2 instances in different availability zones:

* ap-southeast-2b: `403`
* us-west-2b: `200`
* eu-west-1a: `403`

I also tested with creating Digital Ocean Droplets in different data centers:

* SFO3: `200`
* LON1: `200`
* SYD1: `200`

Finally I tested with Heroku Dynos 

* Virginia, USA: `200`
* Ireland, EU: `200`

I expected the Heroku Dyno in Ireland to throw a `403` like the EC2 instance did, but it came back as `200`

**Comment by FarhanAliRaza** [comment]
I had a similar issue with cloudflare.
So I moved the API to a subdomain.
So that I can manage that separately from main site protection.
